name: Cypress End-to-End Tests

on: [push]

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci
        
      - name: Download the build folder
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Run Cypress tests
        run: |
          npx cypress run
          mv cypress/screenshots/cypress/* cypress/screenshots/failed/
          mv cypress/videos/* cypress/videos/failed/
        continue-on-error: true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: cypress/screenshots/failed, cypress/videos/failed
